### ISSUE TITLE
faulty memleak checking by FastMM as memleakmonitor

### ISSUE THREAD

**Issue by codejanovic** [VSoftTechnologies/DUnitX#111]
I have been playing around with DUnitX and the IMemoryLeakMonitor and tried to activate FastMM as MemoryLeak-Monitor.

After activating FastMM as IMemoryLeakMonitor, 95% of my testmethods were leaking  - which is definitely wrong (neither EurekaLog nor FastMM (with ReportMemoryLeaksOnShutdown) were reporting any leaks after the whole test run before). 

So there must be something wrong, but I dont know what ;-) I attached a sample Project here: [Click me](https://drive.google.com/file/d/0B-FXXLiuBAgGZjBKVXhQM2hXTGc/view?usp=sharing)

**Comment by vincentparrett** [comment]
Leak checking is not really usable, because we are using the same memory manager for the framework Int's not really possible to use separate memory managers for different parts of a program in delphi, so it's difficult to separate framework memory usage from test memory usage.

**Comment by altembo** [comment]
Yeah I know .. but at least in DUnit checking for memleaks works just fine. Im gonna check what they do different
