### ISSUE TITLE
Allow testmethod to continue running after failed test

### ISSUE THREAD

**Issue by JBontes** [VSoftTechnologies/DUnitX#114]
Sometimes one testmethod implements multiple tests.  
It would be nice to have an option to log any failures, but allow the test to run in order to detect any subsequent failures as well. 

One option would be to use code like this:

```
  try
    Assert.IsTrue(ResultF = ResultS, 'message');
  except
    LogFailureWithDUnitX('other message');
  end;
```

Can this already be done, if not adding the LogFailure code would be useful.

**Comment by vincentparrett** [comment]
Not really doable with the current design, DUnitX uses exceptions to fail/abort a test (the Assert class does that).

**Comment by JBontes** [comment]
Can't we make a `warn.isTrue` to supplement the assert. Sometimes you really want to see what happens after the first fail.

**Comment by vincentparrett** [comment]
Closing this as won't fix, it would require a major redesign (not sure I know how) to do this. The work around is don't use Assert, as it is designed to abort the test immediately.

**Comment by fabriciocolombo** [comment]
Junit introduced the concept of [@Rule](https://github.com/junit-team/junit/wiki/Rules#errorcollector-rule) that handles this use case, but i don't know how much effort is required for implement similar feature neither how do it myself.
Maybe this will give you new ideas. :smiley:
