### ISSUE TITLE
Registered Tests Fail to be executed

### ISSUE THREAD

**Issue by markhumphreysjhc** [VSoftTechnologies/DUnitX#118]
I have converted a unit from DUnit to DUnitX, and have an old issue - If I include a specific unit (which is large and deeply entangled with the rest of our code), then the registered tests fail to be called. I have isolated down to this specific unit, whilst I can appreciated that this is not enough information to solve it, where can I look to see what is going on? The test fixtures are there, they don't seem to have any tests associated within them.

**Comment by vincentparrett** [comment]
I know this is an old issue, been to busy to look at it lately. Have a look in TDUnitXFixtureProvider.Execute. To make it possible to debug, define DUNITX-DEBUG on your project options to enable debug information in the framework. I'll close this issue, just reply if it looks like it's still a problem and I'll re-open the issue.
