### ISSUE TITLE
Document usage of console test runner for batch execution

### ISSUE THREAD

**Issue by m-baumgartner** [VSoftTechnologies/DUnitX#128]
I'd like to have some documentation explaining how to call my test project from a batch file (in my build sequence).
Ideally it should :
* Continue if all tests passed (so the build sequence can be executed unattended if all passes)
* Stop and prompt user will all errors if some tests failed

I'm aware CI servers are great at doing this but right now i want to stick to my "batch files based" sequence :)

**Comment by m-baumgartner** [comment]
I added this in the wiki section ( [here](https://github.com/VSoftTechnologies/DUnitX/wiki/Command-line-test-execution) ).

However the `--exitbehaviour` option should have options depending on tests execution status (pass vs fail).

I'd like to have a third option value `continueifpassed` that would only allow my script to continue if all selected tests passed.
I'll fill another issue for this.

**Comment by vincentparrett** [comment]
closing since you added another issue for this.
