### ISSUE TITLE
New `continueifpassed` value for `--exitbehaviour` CLI option

### ISSUE THREAD

**Issue by m-baumgartner** [VSoftTechnologies/DUnitX#129]
I'd like to have a third value (in addition to `pause` and `continue) for the`--exitbehaviour` option.

It would only continue if all selected tests passed. Otherwise, it would pause.

Example usage :

```
MyTestProj.exe -exit:continueifpassed
```

**Comment by vincentparrett** [comment]
Shouldn't be difficult to add.

**Comment by vincentparrett** [comment]
Closing as no PR eventuated.
