### ISSUE TITLE
Exception raised when FFailsOnNoAsserts is true should not be ETestFailure

### ISSUE THREAD

**Issue by sglienke** [VSoftTechnologies/DUnitX#131]
It should rather be a derived type so other code can check if it was an actual failure or one caused by this option.

Currently in TestInsight I have to write this code (ugh!)

```delphi
procedure TTestInsightLogger.OnTestFailure(const threadId: TThreadID;
  const Failure: ITestError);
const
  SNoAssertions = 'No assertions were made during the test';
begin
  if Failure.ExceptionMessage = SNoAssertions then
    PostTestResult(TResultType.Warning, Failure)
  else
    PostTestResult(TResultType.Failed, Failure);
end;
```

**Comment by vincentparrett** [comment]
Agreed. Would need to handle the new exception type in the test runner where testfailure is currently handled.

**Comment by sglienke** [comment]
Inherit from ETestFailure so no change is necessary.

**Comment by vincentparrett** [comment]
Closing,  implelemented, throws ENoAssertionsMade
