### ISSUE TITLE
"Invalid Pointer Operation" When Test Fixture Is Reference Counted

### ISSUE THREAD

**Issue by rampaging-poet** [VSoftTechnologies/DUnitX#138]
After converting a unit test from DUnit to DUnitX, I encountered an Invalid Pointer Operation exception when the test runner exits.  The test fixture implemented an interface used by the class being tested and passed itself to an instance of that class in SetupFixture.  When the instance of the class being tested was freed in TearDownFixture, the reference count was decremented appropriately.

Under DUnit, test fixtures were all reference counted and the reference count remained at 1.  In DUnitX, the test fixtures are not reference counted so TearDownFixture causes my test fixture's reference count to reach 0 and be destroyed.  The invalid pointer operation occurs shortly thereafter when DUnitX.TTestFixture attempts to free a test fixture instance that already freed itself.

This issue can be worked around by implementing non-reference-counted versions of _AddRef and _Release or using separate classes for test fixtures and mocks.

I consider this a defect because [Introducing DUnitX](https://www.finalbuilder.com/resources/blogs/postid/697/introducing-dunitx) states that _any_ class can be used as a test fixture, and none of the documentation contradicts that.  However, actually using a reference-counted class results in an unhandled exception.

The issue can be reproduced using the Delphi code below.

```
unit DUnitX_Invalid_Pointer;

interface
uses
  DUnitX.TestFramework;

type
  IParent = interface(IInterface)
    ['{56D2119D-BF9C-4305-8A1C-6CE072F0531C}']
    function GetValue: Integer;
  end;

  //This is the class being tested.
  TChild = class(TObject)
    constructor Create(const AParent: IParent);
  strict private
    FParent: IParent;
  public
    function AddOneToParent: Integer;
  end;

  //This class is a test fixture that also implements a mock version of GetValue;
  [TestFixture]
  TTestChild = class(TInterfacedObject, IParent)
  strict private
    FChild: TChild;
    function GetValue: Integer;
  public
    [SetUpFixture]
    procedure CreateChild;
    [TearDownFixture]
    procedure DestroyChild;

    [Test]
    procedure TestAddOneToParent;
  end;

implementation

constructor TChild.Create(const AParent: IParent);
begin
  inherited Create;
  FParent := AParent;
end;

function TChild.AddOneToParent: Integer;
begin
  Result := FParent.GetValue + 1;
end;

function TTestChild.GetValue;
begin
  Result := 1;
end;

procedure TTestChild.CreateChild;
begin
  FChild := TChild.Create(Self);
  //Our reference count just increased by one.
end;

procedure TTestChild.DestroyChild;
begin
  FChild.Free;
  //Our reference count just decreased by one.  Oh look, it's zero!  Goodbye world.
end;

procedure TTestChild.TestAddOneToParent;
begin
  Assert.AreEqual(2, FChild.AddOneToParent);
end;

end.
```

**Comment by vincentparrett** [comment]
I don't see this as a defect in DUnitX, it just doesn't do reference counting on test fixtures, as they are just plain old classes. My suggestion would be to create a base fixture class which disables reference counting and have your fixtures descend from that, however a better option would be to not use the fixture classes for mocking. 

BTW, the fact that this works in DUnit is a side effect of it's implementation, in that the fixture classes are reference counted. If they changed the implementation, you would end up with the same issue. You are relying on an internal implementation feature, which is a bad idea imho.

**Comment by rampaging-poet** [comment]
Ok, thanks for the quick reply.
