### ISSUE TITLE
IWeakReference<T> contains GUID... it must not!

### ISSUE THREAD

**Issue by LK-Daniel** [VSoftTechnologies/DUnitX#140]
https://github.com/VSoftTechnologies/DUnitX/blob/master/DUnitX.WeakReference.pas#L80

Note that Generic Interfaces in Delphi must not contain a GUID, otherwise incompatible specializations of the same Generic Interface type will be castable without any warning.

**Comment by vincentparrett** [comment]
In most cases I would agree, however I'll have to check if this breaks anything before changing it. I know in  Delphi Mocks removing the guid from generic interfaces caused us problems.

**Comment by vincentparrett** [comment]
Closing as this was fixed in 2018!
