### ISSUE TITLE
Is there a Version for Delphi 10.1 Berlin?

### ISSUE THREAD

**Issue by MarkusSchadegg** [VSoftTechnologies/DUnitX#143]
Is there a Version for Delphi 10.1 Berlin?

**Comment by vincentparrett** [comment]
Delphi 10.1 Berlin ships with DUnitX. I have not yet merged in any changes from berlin, will do that in the comming days.

**Comment by vincentparrett** [comment]
I have synced the changes (not really much) so the github version supports berlin.
