### ISSUE TITLE
Build error on Berlin group project

### ISSUE THREAD

**Issue by Spelt** [VSoftTechnologies/DUnitX#145]
Hi

Just downloaded the latest and tried to build in Berlin.

Got an error, see attachment.

Hope it helps!
![dunitx build error](https://cloud.githubusercontent.com/assets/12660181/14911012/8b91e286-0df2-11e6-8a6f-4c7b08b570f4.png)

**Comment by vincentparrett** [comment]
Strange, compiles here for me. Looks like you are not using the latest inc file.

**Comment by Spelt** [comment]
I used the 'Downloaded zip' button and just extracted it.

2016-04-29 15:43 GMT+02:00 Vincent Parrett <notifications@github.com>:

**Comment by rlove** [comment]
[Delphi.Mocks](https://github.com/VSoftTechnologies/Delphi-Mocks) is not part of the DUnitX Distribution.     It's required to run the unit tests for DUnitX.     It's not required for you to build and run your own unit tests.     You don't need to compile the Tests unless your doing development on DUnitX.

**Comment by vincentparrett** [comment]
Closing, not an issue.
