### ISSUE TITLE
VCL GUI Logger does not update or respond while running

### ISSUE THREAD

**Issue by vincentparrett** [VSoftTechnologies/DUnitX#148]
Looking at this. It's all running in the main thread, so will need some tweaks as the runner is in a tight loop.

**Comment by vincentparrett** [comment]
@rmcginty I have pushed some changes to the GUI logger that makes it update as it's running. Not sure the behavior of changing No Assertions failure to warning is correct, they are generated by the use setting an option to fail when no assertions are made, so really they should be failures.

**Comment by rmcginty** [comment]
I copied that from TestInsight.  If it is preferable the other way, I can definitely change it.  I personally liked the way TestInsight did it and the change only affects the GUI, not the actual failures output in console or XML output.  Up to you though - I'm more than fine with reverting them back to failures.

**Comment by rmcginty** [comment]
I've updated the progress mechanism significantly - now shows test count, current test number, etc.  This is in addition to your progress bar.  Not quite ready to do a PR yet, but just wanted to note that progress has been made on this and is forthcoming.

**Comment by rmcginty** [comment]
Looking at diffs with my current code, I believe that a previous PR must've had all the changes I mentioned in my previous comment.  The UI is definitely responsive when showing the results as it is running...  I think you can close this unless there is something in particular that you feel needs further addressing.
