### ISSUE TITLE
ConvStr2DynArray in DUnitX.Utils doesn't work in XE

### ISSUE THREAD

**Issue by rmcginty** [VSoftTechnologies/DUnitX#152]
While rebasing my fork, I found this line doesn't work in XE:

`elType := ATarget.TypeData.DynArrElType^;`

Looking at the TypInfo source, TypeData is commented out (???).  Unless someone knows a workaround, I think that functionality is just going to have to be conditonalized out for XE and lower.

**Comment by natvincent** [comment]
Same here for 2010.

**Comment by rmcginty** [comment]
Apparently this doesn't work in XE2 either.  I'll try to find a firm answer on what the lowest version supported is and make the necessary conditionals for my next PR.

**Comment by vincentparrett** [comment]
This should now work in XE, the property was introduced in XE3, added suitable ifdefs to deal with this.
