### ISSUE TITLE
DUnitXFiremonleyGUI_XE5 Doesn't build

### ISSUE THREAD

**Issue by rpottsoh** [VSoftTechnologies/DUnitX#153]
Just updated my local copy of DunitX.  Everything else seems to be building OK out of DUnitX_XE5.groupproj except for subject project.

`[dccosx Fatal Error] DUNitX.Loggers.GUIX.pas(36): F1026 File not found: 'C:\Program Files\TMSI Delphi XE5 Libs\DUnitX\FMX.ListView.Appearances.dcu'`

**Comment by rmcginty** [comment]
My understanding from @vincentparrett is that the FireMonkey GUI logger doesn't compile in at least XE7 and lower.  Not sure what the exact minimum required version is, but I believe Embarcadero contributed that code and it only worked with the version that they originally wrote it for and higher.

**Comment by rmcginty** [comment]
@vincentparrett - See my previous comment.  Is this correct?  If so, do you want to close this?  I don't think any of us are going to be working on the FMX version anytime soon, but if you prefer to leave it open just in case, then that's cool too.

**Comment by vincentparrett** [comment]
Closing, have no intention of working on the fmx version, that's embarcadero's baby. Dealing with fmx between delphi versions is a nightmare, vcl was bad enough but fmx changes every version and breaks forms.

**Comment by Nashev** [comment]
On the page https://github.com/VSoftTechnologies/DUnitX in Readme it's feel like any own GUI is deprecated here,  in favor of using TestInsight (https://bitbucket.org/sglienke/testinsight/wiki/Home)
