### ISSUE TITLE
How to implement the new GUI runner (XE5)

### ISSUE THREAD

**Issue by rpottsoh** [VSoftTechnologies/DUnitX#154]
1.  Just poking around the new code and it isn't obvious to me how to a convert console test to a gui test.  I see that DUnitX.Loggers.GUI.VCL.pas has procedure Run, but do not know if I need to be calling this from the DPR, or if this is handled in another fashion.  Tried creating a new DUnitX project, but the IDE expert made no mention of the new GUI test runner interface.
2.  Also Delphi insists that System.Actions be at the tail end of the interface sections uses statement, even though it does appear there already.  I had to rem the occurrence that appears earlier in the Uses. 
3.  Not a big deal, I have come across this before...  Apparently rchText.Zoom property doesn't exist in XE5.  I'm assuming that just the property value is lost when I ignore this.

I've made a futile attempt to utilize the GUI runner by adding DUnitX.Loggers.GUI.VCL to the uses in the DPR.  I've also defeated {$Apptype Console}.  Inserted a call to Run after //Run tests and commented the three lines that normally appear after //Run tests in the DPR.

Any instruction that you can offer is appreciated.  I sense that I am on the bleeding edge here and perhaps just need to be patient.  :)

Thanks, looking forward to utilizing the GUI.

Ryan

**Comment by rpottsoh** [comment]
I see there is already an issue from @rmcginty that addresses the IDE expert.  Please disregard my previous remarks regarding the IDE Expert.

**Comment by rmcginty** [comment]
I'm going to be updating the wiki and the IDE expert, but in the meantime I took a new project file and made the modifications to show how it is used.  Basically just look for the GUI IFDEFs for what needs to be added.  Then simply define "GUI" in your project properties conditional defines and go.
```
program Project1;

{$IFNDEF GUI}
{$IFNDEF TESTINSIGHT}
{$APPTYPE CONSOLE}
{$ENDIF}
{$ENDIF}

{$STRONGLINKTYPES ON}

uses
  SysUtils,
{$IFDEF TESTINSIGHT}
  TestInsight.DUnitX,
{$ENDIF}
{$IFDEF GUI}
  DUnitX.Loggers.GUI.VCL,
{$ENDIF}
  DUnitX.Loggers.Console,
  DUnitX.Loggers.Xml.NUnit,
  DUnitX.TestFramework;

var
  runner : ITestRunner;
  results : IRunResults;
  logger : ITestLogger;
  nunitLogger : ITestLogger;
begin
{$IFDEF TESTINSIGHT}
  TestInsight.DUnitX.RunRegisteredTests;
  exit;
{$ENDIF}

{$IFDEF GUI}
  DUnitX.Loggers.GUI.VCL.Run;
  exit;
{$ENDIF}

  try
    //Check command line options, will exit if invalid
    TDUnitX.CheckCommandLine;
    //Create the test runner
    runner := TDUnitX.CreateRunner;
    //Tell the runner to use RTTI to find Fixtures
    runner.UseRTTI := True;
    //tell the runner how we will log things
    //Log to the console window
    logger := TDUnitXConsoleLogger.Create(true);
    runner.AddLogger(logger);
    //Generate an NUnit compatible XML File
    nunitLogger := TDUnitXXMLNUnitFileLogger.Create(TDUnitX.Options.XMLOutputFile);
    runner.AddLogger(nunitLogger);
    runner.FailsOnNoAsserts := False; //When true, Assertions must be made during tests;

    //Run tests
    results := runner.Execute;
    if not results.AllPassed then
      System.ExitCode := EXIT_ERRORS;

    {$IFNDEF CI}
    //We don't want this happening when running under CI.
    if TDUnitX.Options.ExitBehavior = TDUnitXExitBehavior.Pause then
    begin
      System.Write('Done.. press <Enter> key to quit.');
      System.Readln;
    end;
    {$ENDIF}
  except
    on E: Exception do
      System.Writeln(E.ClassName, ': ', E.Message);
  end;
end.
```

**Comment by rmcginty** [comment]
As for 2 and 3, opening the actual form in the designer for anything over XE is problematic as the form designer constantly tries to update the uses clause since it doesn't seem to acknowledge or respect IFDEFs.  I tried everything I could think of (putting conditionals in the middle of the word "uses" etc to try and trick the codegen) but never found any combination that worked.  Even tried a single uses clause with namespaces like {$IFDEF USE_NS}System.{$ENDIF}Classes, but the codegen blocked me at every turn...

The zoom property is because @vincentparrett worked on it in XE7 (I believe) when he added the much needed progress bar and such - the IDE added the properties to the dfm.  They can be safely ignored and on my next PR, I'll make sure to edit in XE to eliminate that issue moving forward.

**Comment by rpottsoh** [comment]
@rmcginty thanks for getting back to me so quickly.  Sorry it has taken me so long.  I implemented your suggestions into my DPR and the GUI runner works great.  I did run into a minor issue with one my of my tests failing that has no assertions.  That test uses Delphi Mocks Verify capability instead....  I was able to clear this issue by assigning FailsOnNoAsserts to False in function NeedRunner in DUnitX.Loggers.GUI.VCL.  I'm thinking this might need to be a property that would be accessible as it is for the console runner, in the DPR.

So far this has been the only issue I have stumbled upon with the new GUI runner.  Otherwise it works well.  Thanks for taking the time to make it.

Ryan Potts

**Comment by rmcginty** [comment]
@vincentparrett I think you can close this one too.  All of the code for the project sample I posted will be generated by the new expert changes coming very soon.

**Comment by rpottsoh** [comment]
@rmcginty any plans to address the assignment of FailsOnNoAsserts?  Should this become a seperate issue?

**Comment by rmcginty** [comment]
@rpottsoh Let me look at whether I've got anything for that in my local version.  If not, I can add it as a feature to the expert like I have the case sensitivity for Assert.  Will update this later today with more info.

**Comment by rmcginty** [comment]
@rpottsoh I'm still thinking on this.  It is a bit more complicated than I remembered, but it is on my radar.  I'm thinking we probably should open another issue, but I'm not exactly sure what it the question it should ask is yet.  I've got to look at a few other things in the code later today or tomorrow, so I'll try to remember to circle back and update this.

**Comment by rpottsoh** [comment]
Thanks, I mainly didn't want it to get missed if this issue was going to close.

**Comment by vincentparrett** [comment]
I'm closing this issue as the original questions have been dealt with. If there is another question, please open a new issue.

**Comment by Nashev** [comment]
On the page https://github.com/VSoftTechnologies/DUnitX in Readme it's feel like any own GUI is deprecated here,  in favor of using TestInsight (https://bitbucket.org/sglienke/testinsight/wiki/Home)
