### ISSUE TITLE
Can't compile DUintX.Generics.hpp with clang compiler

### ISSUE THREAD

**Issue by rkorn** [VSoftTechnologies/DUnitX#156]
I get the following error:

[CLANG Error] DUnitX.Generics.hpp(85): use of undeclared identifier 'Items'

I'm using C++Builder 10 Seattle Subscription Update 1

**Comment by vincentparrett** [comment]
Apologies for not responding earlier, limited time etc. I don't use C++ Builder so not sure how this could be solved. Might be better to ask on emb forums
