### ISSUE TITLE
DUnitX_IDE_Expert_D10Berlin.dproj will not compile due to missing packages in RAD Studio 10.1 or 10.1 update 1

### ISSUE THREAD

**Issue by rmcginty** [VSoftTechnologies/DUnitX#160]
I've posed the question on the Google+ Delphi and DUnitX and not received any definitive responses, so wanted to open an issue to get some feedback.  

I have installed Berlin 3 times, and Berlin update 1 also 3 times.  Opening the expert project and trying to compile results in:

[dcc32 Fatal Error] DUnitX_IDE_Expert_D10Berlin.dpk(36): E2202 Required package 'ExpertsCreators' not found

This package is used by the DUnitX.Expert.ProjectWizardEx.pas and a few other files.  The problem is the DCP for this package is nowhere to be found.  The BPL is there, but that doesn't help compiling.  Likewise, the actual source files are missing as well (ExpertsRepository, et al).  The files WERE available in Seattle (in lib\win32\release and other lib folders), so I don't know what happened to them in Berlin.  I use a rather stripped down install of the IDE, so I'm curious if anyone else can verify they do or do not get this same error - perhaps my install options are affecting these files being installed.

As of now, I just need someone to tell me that they can or cannot compile the expert, because I cannot and have no known workaround for the missing files.

**Comment by vincentparrett** [comment]
Hi Ryan

On my berlin (haven't installed the update) install the file is in

c:\Program Files (x86)\Embarcadero\Studio\18.0\lib\win32\debug

and

c:\Program Files (x86)\Embarcadero\Studio\18.0\lib\win32\release

I have berlin enterprise so perhaps it's missing from other sku's (like pro edition)?

**Comment by vincentparrett** [comment]
I'm wondering if it depends on which installer you used? Unfortunately I don't recall if I used the getit installer or the iso.

**Comment by rmcginty** [comment]
Well, that's promising.  I am using the Pro edition, but I did select only the bare minimum via the getit installer.  I will try a couple of different things and update this issue with my findings.

**Comment by baeckerg** [comment]
The files are missing on my Berlin as well (using Radstudio Pro Edition, ISO Installer). Will check tonight on my other machine whether it is missing in Update 1 as well

**Comment by johnfidel** [comment]
Just installed Berlin Update 1. Package "ExpertsCreators240.bpl" is available in bin directory. I've installed it with the components installer but still the error:

> [dcc32 Fatal Error] DUnitX_IDE_Expert_D10Berlin.dpk(36): E2202 Required package 'ExpertsCreators' not found.

**Comment by johnfidel** [comment]
@rmcginty: Yes of course you are right and yes I am using professional with mobile version. What ever it is, hope they realize it soon.

**Comment by johnfidel** [comment]
I just realized what I was doing wrong! In XE7 i had the DUnitX_IDE_Expert Project inside my Groupproject. Well in Berlin the DUnitX Framework is allready integrated. After removing the DUnitX Framework of my Groupproject and do some modifications in the DUnitX.dpr file everything works perfectly fine!

**Comment by rmcginty** [comment]
Well, the package is integrated, but I'm trying to actually make changes to it and thus need to compile it.  I remove the "pack in" version included so I can use the latest source and make changes.  The expert doesn't actually have anything to do with the functionality of DUnitX - it only gives it the IDE tie-ins for creating units and projects.  You can compile the test framework fine in 10.1 - you just can't compile the expert package.  I'm still trying to get verification that the files were removed from the Pro sku and whether that change was intentional or not.

**Comment by rmcginty** [comment]
After posing the question on the 10.1 Update 2 webinar, Marco told me to email directly, which I did.  I will update once I get an answer back.

**Comment by JohnTerwiske** [comment]
Did you get it to work?  I have the same issue here with Berlin update 1, and yes I also need to make some changes to source (for my own savage amusement)

**Comment by rmcginty** [comment]
Not yet - he has responded asking me for some specifics about my setup.  Will update again soon.

**Comment by rpottsoh** [comment]
@rmcginty any news on this issue?  I am evaluating the Starter Edition and am having the same difficulty, ExpertsCreators.dcp is missing.  Perhaps I am dealing with a limitation of the starter edition.

**Comment by rmcginty** [comment]
@rpottsoh No, I've emailed several times and also installed 10.2 which has the same issue.  I'm not sure what else to do at this point.

**Comment by rpottsoh** [comment]
I've managed to get DUnitX to work, just created project manually.  I've not tried the gui test runner.  At this point I see no reason it shouldn't work.  Thanks for the reply. 

Sent from my android device.

**Comment by rmcginty** [comment]
It will definitely work, it is just that you can't install (or work on) the experts that tie into the IDE.  I may have to defer those to someone that has a higher sku than mine once I commit my changes to the experts...

**Comment by vincentparrett** [comment]
I just emailed Marco about this as it's not just us with this issue. Hopefully they can make the file available either through an update or just make the file available for download.

**Comment by rpottsoh** [comment]
It is interesting that the help system has a section on DUnitX, but it isn't included in the starter edition.  It is too bad that they opted to leave out a unit testing frame work.

Sent from my android device.

**Comment by vincentparrett** [comment]
@rpottsoh not sure why they did that, considering it's open source anyway.

**Comment by vincentparrett** [comment]
Closing this, it's not a DUnitX issue, it's an embarcadero delivery issue.
