### ISSUE TITLE
EEFACE in DunitX test resets floating point control word in other tests

### ISSUE THREAD

**Issue by ville-v** [VSoftTechnologies/DUnitX#161]
Steps to reproduce:

1. Disable floating point exceptions in _tmain with `_control87(MCW_EM, MCW_EM);`
2. Do something in one test, which would normally cause floating point exception, such as division by zero
3. Tests run normally
4. Change some other test, so that it throws external exception EEFACE
5. The former test now causes floating point exception, even though they were disabled in _tmain

Expected behavior:

The other test should not cause floating point exceptions in any case, because they were disabled in _tmain.

Environment:

C++ Builder 10.1, new Clang compiler, C++ language
Using version of DunitX that came with C++ Builder 10.1: "rev: 31.00 (Windows)"
Developing on Windows 7, building for 32-bit Windows target

I have made identical bug report to Embarcadero, in case this is a bug in the compiler: https://quality.embarcadero.com/browse/RSP-15899

**Comment by vincentparrett** [comment]
As far as I know, DUnitX does not do any enabling/disabling floating point exceptions, so my guess is the rtl or other external code would be the culprit.

**Comment by vincentparrett** [comment]
Closing, if you have a reproducable test case, submit a pull request with a failing test added to the Tests project.
