### ISSUE TITLE
EIntOverflow error in TDUnitXFixtureResult.RollUpResults

### ISSUE THREAD

**Issue by Daniel-Tr** [VSoftTechnologies/DUnitX#163]
Hi,

we're recently running into an EIntOverflow error in TDUnitXFixtureResult.RollUpResults when executing tests. The issue is only reproducable with a higher amount of fixtures and tests (for us: 280 tests with a total of 155 fixtures).

For me, it seems like this happens because of two overlapping recursion mechanisms. Each fixture executes its child fixtures. Then the results for this fixture are calculated in RollUpResults by summarizing the results from all children (recursive). 

A possible solution could be to:
1.  in DUnitX.FixtureResult, remove line 356 ("(fixture as IFixtureResultBuilder).RollUpResults;")
2. in DUnitX.TestRunner, remove line ~650 ("context.RollUpResults;") and add after line 644 (ExecuteFixtures):  (fixtureResult as IFixtureResultBuilder).RollupResults;

Please let me know if this solution seems correct and if I shall commit the changes.

STACKTRACE:
date/time          : 2016-10-12, 12:48:58, 804ms
operating system   : Windows 10 x64 build 10586
system language    : German
system up time     : 4 hours 9 minutes
program up time    : 1 minute 19 seconds
processors         : 4x Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
physical memory    : 4110/7854 MB (free/total)
free disk space    : (C:) 76,64 GB (D:) 70,16 GB
display mode       : 1920x1200, 32 bit
process id         : $10dc
allocated memory   : 144,35 MB
largest free block : 1,98 GB
executable         : Tests.exe
exec. date/time    : 2016-10-12 12:47
compiled with      : Delphi 10.1 Berlin
madExcept version  : 4.0.15
Bitness            : 32 Bit Edition
CrashedThreadID    : $1928
.NET Version (4.x) : 4.6.01038
callstack crc      : $d889bcbc, $dd744175, $6657e76d
exception number   : 1
exception class    : EIntOverflow
exception message  : Integer overflow.

main thread ($1928):
005f8c43 Tests.exe    DUnitX.FixtureResult 362 +12 TDUnitXFixtureResult.RollUpResults
005eefab Tests.exe    DUnitX.RunResults    251  +4 TDUnitXRunResults.RollupResults
006089c6 Tests.exe    DUnitX.TestRunner    687 +41 TDUnitXTestRunner.ExecuteFixtures
0060894c Tests.exe    DUnitX.TestRunner    673 +27 TDUnitXTestRunner.ExecuteFixtures
0060858c Tests.exe    DUnitX.TestRunner    611 +28 TDUnitXTestRunner.Execute
00a84dd2 Tests.exe    Jam.Test             570 +19 RunRegisteredTests
00ef6624 Tests.exe    Tests                 22  +4 initialization
753138f2 KERNEL32.DLL                              BaseThreadInitThunk

**Comment by vincentparrett** [comment]
Nice catch, just pushed a fix.. context.RollupResults should have only been called once, after all fixtures have run.
