### ISSUE TITLE
Running DUnitX with NUnit logger on Android platfrom results in error 

### ISSUE THREAD

**Issue by PropheticBird** [VSoftTechnologies/DUnitX#172]
I try to run this simple code under Android (API 23) and it results in an error: "Object lock not owned": 
```
  nunitLogger := TDUnitXXMLNUnitFileLogger.Create(TPath.Combine(TPath.GetSharedDocumentsPath, 'test_results.xml'));
  runner := TDUnitXTestRunner.Create(nunitLogger);
  runner.FailsOnNoAsserts := True;
  results := runner.Execute;
  results.FixtureResults;

  Sleep(50);
```
It looks like the error happens in the TMonitor class when DUnitX object is destroyed. 

I'm not very experienced with Delphi, but shouldn't there be a way to run some user specific operation after DUnitX has finished executing? 
Same code works fine and produces no error if I run it it on Win64 platform.
I use RAD Studio Berlin Update 1.

Thanks for you time looking into it.

**Comment by vincentparrett** [comment]
I don't use delphi for mobile dev so can't help with that. The mobile support was added by embarcadero so you will need to ask them.
