### ISSUE TITLE
Lack of DUnitX in Delphi Starter Edition

### ISSUE THREAD

**Issue by rpottsoh** [VSoftTechnologies/DUnitX#174]
@vincentparrett I am building an object pascal track at exercism.io.  At the moment it is featuring Delphi and DUnitX.  Not having your code as part of the starter edition adds a layer of complexity for the student that is trying out object pascal for the first time and is using the starter edition.  Documenting for them, on exercism.io site, on how to manually setup DUnitX is not the end of the world; it would just be nice if it wasn't necessary.  It should only be necessary for those that would happen to be using a version prior to XE8 (I believe?).  I thought it better to mention this as a new issue then to tack it on to #160.

**Comment by vincentparrett** [comment]
I have no control over what embarcadero bundle with the starter edition. As for documentation, well that's always a problem with open source projects. I have very limited time to work on DUnitX these days, so I can only hope that someone else might be interested in contributing.
