### ISSUE TITLE
How do I install DUnitX?

### ISSUE THREAD

**Issue by jmuehlenhoff** [VSoftTechnologies/DUnitX#175]
Is there a package for DUnitX itself?

We only found the package for the IDE Expert.

The [wiki page](https://github.com/VSoftTechnologies/DUnitX/wiki/Getting-Started) only has instructions for installing the Wizard as well.

**Comment by rlove** [comment]
There is not a package for DUnitX   The IDE Expert is the same thing as the Wizard.

**Comment by rmcginty** [comment]
As @rlove  said, there is nothing to "install" unless you want IDE experts which can help you create the boilerplate code for a DUnitX project.  Otherwise, it can easily be built by hand (look at the example test project for a good sample) and just involves making sure DUnitX source is on your search path.

If that doesn't get you started in the right direction, let me know and I'll go into more detail when I get a little bit of free time today or tomorrow.

**Comment by rpottsoh** [comment]
@jmuehlenhoff as @rmcginty stated earlier there is really nothing to install.  There is only an expert that can be compiled and plugged into Delphi.  The expert isn't necessay to use DUnitX as long as you know what to put in your DPR file or have an example to refer to.

However, you do need to make two adjustments to Delphi so it knows where to find DUnitX:

1.  You should create a DUNITX environment variable that points to the location where you stored your copy of DUnitX.  Under Tools -> Options -> Environment Variable you will want to create a `New...` variable.  A `New User Variable` window will appear when you clicked New.  Set Variable name to DUNITX and Variable Value to the full path to where you keep DUnitX.  Click OK

2. At this point you may decide to add the variable you just created to the search path in each project where you utilize DUnitX or you could add the variable to the Library path which will delphi to find DUnitX for all projects.  The Library path is in Options -> Delphi Options/Library -> Library path.  When refering to a variable it should be noted like so `$(DUNITX)`.

If you are using the Starter Edition of Delphi you will not be able to use the expert that is supplied with DUnitX.  I think DUnitX comes with versions XE8 and up, but I can't speak to the state it is in after the initial install of Delphi, I am using XE5 myself.

These steps are based on the Starter Edition of Delphi and I have compared them against XE and XE5 so without knowing what version you are using you should have a good chance for success.

**Comment by jmuehlenhoff** [comment]
That sounds unconventional to me.

Normally I'd have expected a DUnitX package that is compiled once and then added to the library path, like with any other third party Delphi library.

Thanks for the clarification, you might want to add that to the wiki page and / or README though.

**Comment by vincentparrett** [comment]
Nothing unconventional about it, you install components, with libraries you just reference them. There is no runtime package for DUnitX as it's just not needed.
