### ISSUE TITLE
Status of Build\TestAndBuild.fbp7?

### ISSUE THREAD

**Issue by rmcginty** [VSoftTechnologies/DUnitX#187]
I went to look at this file today and it looks like something has destroyed it via encoding or something.  I couldn't open it in FB7, nor FB8, and looking at the raw file will show you why.

I was curious if it was even applicable now that Continua is used to monitor the repo.

**Comment by vincentparrett** [comment]
This file isn't used, but it might be useful to resurrect it. I'll try and come up with something.
