### ISSUE TITLE
Are we using result or Result?

### ISSUE THREAD

**Issue by rmcginty** [VSoftTechnologies/DUnitX#188]
While cleaning up any code that I touch, the biggest thing I notice that is inconsistent is whether result is capitalized or not.  I personally do "Result", but I'm open to whatever is preferred by the people that contributed the bulk of the code.  I just want to know so I can get it more consistent as I come across it.

**Comment by vincentparrett** [comment]
I don't really have a preference, but since I spend more time writing c# than delphi these days, I tend to go with lowercase if I think about it, but often with code completion etc it ends up capitalized, I don't bother changing it. Fell free to make it consistent if you must ;)
