### ISSUE TITLE
GUI Runner support ?

### ISSUE THREAD

**Issue by VictorSFaria** [VSoftTechnologies/DUnitX#19]
There is a prototype of a GUI Logger in the project, do you have the intended in support this type of logger? And why did you use VCL and not Firemonkey ?

**Comment by Nashev** [comment]
On the page https://github.com/VSoftTechnologies/DUnitX in Readme it's feel like any own GUI is deprecated here, in favor of using TestInsight (https://bitbucket.org/sglienke/testinsight/wiki/Home)
