### ISSUE TITLE
How do you pass arguments that include variable names?

### ISSUE THREAD

**Issue by dtamade** [VSoftTechnologies/DUnitX#196]
const
  TestSource = '@CDAB@CD@CD@EF@GH@;';
  TestP2 = True;
---------------------------------------
[TestCase('Test1',!!TestSource,TestP2!!)]
--------------------------------------------------
How to do?

**Comment by rpottsoh** [comment]
Does this work?

```pascal
const
  cTest = '@cdab@CD@CD@EF@GH@,true';
```
```pascal
[TestCase('Test1',cTest)]
```

I have never tried passing a const as a parameter to an attribute, I have only ever needed inline strings.

**Comment by dtamade** [comment]
These test constants,
I now put them in the test initialization code
It's just a drop in flexibility
It's settled
Text parsing doesn't seem like a good idea.

Machine Translation... I hope you understand.

**Comment by rpottsoh** [comment]
I don't fully comprehend what you are saying, but it appears as though you have solved or otherwise worked around the issue you were having.  :1st_place_medal:
