### ISSUE TITLE
Missing 'SStrEmpty' when being compiled for WIN64 under XE4, since commit c67d3b1b09c5e03199c6121be7e5cdaf0f8b4ba3

### ISSUE THREAD

**Issue by edwinyzh** [VSoftTechnologies/DUnitX#198]
Since [commit c67d3b1b09c5e03199c6121be7e5cdaf0f8b4ba3 on Apr 5, 2017 by ](https://github.com/VSoftTechnologies/DUnitX/commit/c67d3b1b09c5e03199c6121be7e5cdaf0f8b4ba3)
When compiling under **XE4** for **win64**, I'll get this error message:
`[dcc64 Error] DUnitX.Assert.pas(812): E2003 Undeclared identifier: 'SStrEmpty'`

**Comment by vincentparrett** [comment]
I don't have XE4 installed to test this, but will accept a pull request to fix this.

**Comment by vincentparrett** [comment]
I can't see how this can happen. Can you point to the change that in that commit that actually caused the problem ?

**Comment by vincentparrett** [comment]
Closing, cannot reproduce. The constant is in DUnitX.ResStrs which is referenced in the implementation section uses clause of DUnitX.Assert
