### ISSUE TITLE
Typo in DUnitX.TestFramework.IFixtureResult

### ISSUE THREAD

**Issue by hubalazs** [VSoftTechnologies/DUnitX#208]
DUnitX.TestFramework.pas
property IFixtureResult.Pesses should be Passes

**Comment by rpottsoh** [comment]
Nice find.  [Line 323](https://github.com/VSoftTechnologies/DUnitX/blob/d5861ce0de6a9fbfdc8c158b0b1c8614082c188d/DUnitX.TestFramework.pas#L323).  I imagine if you created a PR to fix this it would be appreciated.

**Comment by hubalazs** [comment]
https://github.com/VSoftTechnologies/DUnitX/pull/209
