### ISSUE TITLE
Re-run last failed tests

### ISSUE THREAD

**Issue by alexvulpe** [VSoftTechnologies/DUnitX#210]
Hi, 
would be nice to have a command line switch that will allow to re-run the tests failed during last execution (from dunitx-results.xml file).

**Comment by rpottsoh** [comment]
Are you changing the code under test before running the failed tests again?  If you are changing the code wouldn't you also want to run the passing tests as well, to make sure changes to the code under test didn't break any of those tests?

I am curious to understand the benefit gained from such a command line switch.

Execute your test EXE with a `/h` command line switch.  There are several commands available that, with a little effort, would probably provide you with what you need.

**Comment by alexvulpe** [comment]
Yes, I am changing the code under test before running the failed tests again.
My idea is that my code change is done *primarily* to fix the failed tests.
Then, if failed tests are OK, I will *definitely* re-run the whole bunch of tests.

Imagine the situation when running the entire set of tests takes 20 minutes (which is close to what I have now, couple of hundreds of tests, querying different databases). It does not worth to run the entire bunch, I'm interested to see if my fix worked for couple of failing tests, then, if failing tests pass, I will rerun the entire set.

I hope you see my point of view :)

**Comment by alexvulpe** [comment]
On the other hand, after checking the source code of DUnitX, I have realised that it's simpler to create a logger class descending from TDUnitXNullLogger, that will collect the failed tests and save them as a list, and add it to runner. Then pass this file as parameter with -rl.
Easy and simple :)

**Comment by vincentparrett** [comment]
DUnitX already supports filtering which tests to run, although it may need some tweaking for this scenario, and you may need to create a file to pass with the options as there is a limit on the length of the command line on windows (varies with versions).

**Comment by alexvulpe** [comment]
Hi Vincent,
thanks for details. I'm collecting the failed tests with logger and passing them with -rl parameter, all works good.
