### ISSUE TITLE
Runner fails to run, with "I/O Error 105" (Unable to write to console)

### ISSUE THREAD

**Issue by mWaltari** [VSoftTechnologies/DUnitX#214]
For reason or other sometimes it seems that console is not ready when test are already running, and logging to console fails. Same project runs fine with TestInsight. dpr code underneath.

I have no idea why and what and how, but just this happens at least on my dev box at work. I've seen also that it fails most of the time, but not 100% always, so maybe some part of the code shoudl wait for the console to appear, just a guess.

Io-exception happens at results := runner.Execute;

... dpr ...
  logger := TDUnitXConsoleLogger.Create(true);
    runner.AddLogger(logger);
    //Generate an NUnit compatible XML File
    nunitLogger := TDUnitXXMLNUnitFileLogger.Create(TDUnitX.Options.XMLOutputFile);
    runner.AddLogger(nunitLogger);
    runner.FailsOnNoAsserts := False; //When true, Assertions must be made during tests;

    //Run tests
    results := runner.Execute;

Call stack:
DUnitX.Windows.Console.TDUnitXWindowsConsoleWriter.InternalWriteLn(???)
DUnitX.Windows.Console.TDUnitXWindowsConsoleWriter.InternalWriteLn('DUnitX - [STCommon.UnitTests.exe] - Starting Tests.')
DUnitX.ConsoleWriter.Base.TDUnitXConsoleWriterBase.WriteLn('DUnitX - [STCommon.UnitTests.exe] - Starting Tests.')
DUnitX.Loggers.Console.TDUnitXConsoleLogger.OnTestingStarts(28176,1548,1548)
DUnitX.TestRunner.TDUnitXTestRunner.Loggers_TestingStarts(28176,1548,1548)
DUnitX.TestRunner.TDUnitXTestRunner.Execute

**Comment by vincentparrett** [comment]
I've not seen this, but someone else has mentioned it to me before. I've not been able to reproduce this, or find a cause. It's supposed to be a console program, in which case windows provides the console, and we should be able to write to it immediately, I'm not sure what else we could do for this?

**Comment by vincentparrett** [comment]
FWIW - the delphi doco says this

105 | File not open for output | Reported by Write or Writeln on a text file if you do not generate a Console application.

**Comment by rpottsoh** [comment]
Are you able to reproduce this on another computer?  Are you able to put your code online (in a repo) that others could look at, to see if we can reproduce the symptom?

**Comment by mWaltari** [comment]
As so far no one else has complained about this.

I can try make small test, from scratch, and see if it'll have same problem at first place.

I know this is weird thing and as far as I know it should not happen. SHould just work, the console app stuff. 

I'll try to get back today on this...

**Comment by mWaltari** [comment]
OK,

If I make project from the scratch, it works OK.

I was thinking that could it be something in our code. Maybe in some initialization section we have some code that messes delphi console app.  Like some Forms.pas-call etc, that'll just make Vcl to decide, we must be Regular Windows app??

This is not supercritical, but if we can crack this mystery, it would be good for others also. Maybe there is some trap you can set off, easily if you don't realize...

**Comment by rmcginty** [comment]
What version of Delphi are you using?

Maybe the unit init order or function inlining is part of the difference when creating a new project?

**Comment by mWaltari** [comment]
Latest version of delphi ios in use.

**Comment by mWaltari** [comment]
This is bit flaky... And weird... Now it worked OK, with both problematic UnitTest projects misbehaved previously. What in earth is going on :(

**Comment by vincentparrett** [comment]
I just hit this issue on a project (delphi mocks tests) and it took me a while to figure out - it was caused by the project not actually being compiled as a console application (in the linker settings). HTH.

**Comment by mWaltari** [comment]
We FINALLY figured this out, on was simpler program which had exact same problems, aways ha I/O error 105 at startup.

Seems that was fault of a LockBox: Check issue report at here : https://github.com/TurboPack/LockBox3/issues/17

**Comment by vincentparrett** [comment]
Wow, that's nuts.. why would that code need that set? anyway, glad you figured it out.

**Comment by mWaltari** [comment]
Don't know why... 

Maybe some accident copy paste error etc, and nobody happened to get hit by it.

Maybe that was also matter of order in which units were introduced in projekt.

**Comment by mWaltari** [comment]
I think (don't know) that if console stuff was up and running before compiler saw that Unit and then maybe it was OK (or other way around :) )

**Comment by mdanninger** [comment]
I was just able to solve the same problem. I actually found a {$APPTYPE GUI} statement at the start of a testunit of my DUNITX application. (Was accidentally inserted with a keyboard shortcut).
