### ISSUE TITLE
Run on android

### ISSUE THREAD

**Issue by JensFudge** [VSoftTechnologies/DUnitX#217]
Hi,
I am trying to get a test to run on my Android device.
After getting through the errors with missing splash screens by adding them manually I finally got the appdeployed to my Android device.
But, it wont run. I have tried to set a breakpoint on the first line:
TDUnitX.CheckCommandLine;
But it doesnt even get to there. The Delphi IDE get stuck with the "launching" screen.
Any suggestions?

**Comment by MHumm** [comment]
Is the resulting app a console one or a FMX one? I'm asking, because console apps are not yet supported on Android. You might want to vote for ma QP report about this here: [https://quality.embarcadero.com/browse/RSP-17631](url)

**Comment by JensFudge** [comment]
Oh... this was two months ago..
I gave it up and decided to go for another framework in stead.
I was trying to build a FMX app.

**Comment by JensFudge** [comment]
Hi Markus
Thanks for the mail...
But this was an issue two months ago..
I gave it up and went with another framework in stead.

Sorry...

Kind regards
Jens Fudge

Sendt fra min iPhone

**Comment by MHumm** [comment]
Other unit testing framework or other programming language and gui
framework?

Am Sa., 12. Jan. 2019 20:50 hat Jens Fudge <notifications@github.com>
geschrieben:
