### ISSUE TITLE
EOutOfMemory when using Conv2DynArray

### ISSUE THREAD

**Issue by Godwottery** [VSoftTechnologies/DUnitX#220]
I want to run tests to check if my handling of arrays is correct.  In order to do this, I have created a test as below. In order to run this test I have to use DUnitX from GitHub, as the one included in 10.2 does not have support for the conversion functions. 

Now the problem: 
when I compile for "32-bit Windows" - The conversion does not seem to work, and I can not place break-points in the included units. 
when I compile for "64-bit Windows" - I get an EOutOfMemory exception.

Am I somehow including the wrong units, using the built-in ones, or doing something else wrong?

```
[Test]
    [TestCase('TestA','[1,2,3],3')]
    [TestCase('TestB','[3,4],2')]
    procedure Test2(const AValue1 : TArray<Integer>; const AValue2: Integer);
```
```
procedure TMyTestObject.Test2(const AValue1 : TArray<Integer>; const AValue2: Integer);
begin
  Assert.AreEqual<Integer>(Length(AValue1),AValue2);
end;
```

**Comment by luebbe** [comment]
I haven't checked your specific case, but it reminds me of a problem that I had in passing sets to a test case in DUnitX. See this SO question: https://stackoverflow.com/questions/35009927/can-i-pass-a-set-to-a-test-case-in-dunitx.

**Comment by Godwottery** [comment]
Thanks for the link, I stumbled on that one originally when I was looking for a solution to my problem. 
Rechecking my work - I found that I clearly have a syntax error. So I updated my test cases

´´´
[TestCase('TestA','1;[1]',';')]
    [TestCase('TestB','2;[3,3]',';')]
    [TestCase('TestB','5;[1,2,3,4,5]',';')]

    procedure Test2(const AExpected : Integer; const ABytes: TArray<Integer>);
  end;
´´´
´´´
procedure TMyTestObject.Test2(const AExpected : Integer; const ABytes:
    TArray<Integer>);
begin
  Assert.AreEqual<Integer>(AExpected,Length(ABytes));
end;
´´´

Works find for Win32 (ie the tests pass), but I still get an EOutOfMemory exception when running on Win64.

**Comment by vincentparrett** [comment]
Add a define DUNITXDEBUG in your project settings so you can step into DUnitX and see where the error occuring. I would strongly suspect this is a bug in Delphi 10.2 rather than in DUnitX.

**Comment by Godwottery** [comment]
I believe that I have localized the error to the ConvStr2DynArray function, but I am not sure whose fault it is. 
```
DynArraySetLength(p, ATarget, 1, @i);
```
gets called with 
```
p = nil, 
ATarget = (tkDynArray, TArray<System.Integer>)
i = 1
```
This then leads DynArraySetLength to fail on 
```
t := PDynArrayTypeInfo( ... ) // line 34972
```
here t is returned with a kind-field that is "(out of  bound) 114" and elType-field that is nil, this then breaks code further down. 

It does seem that the bug is in Delphi 10.2, but I would like someone else to confirm it.

**Comment by michaelstaszewski** [comment]
Declare "i" as NativeInt in ConvStr2DynArray. I will submit a patch.
