### ISSUE TITLE
Is there a DUnitXRuntime.bpi file or DUnixRuntime.lib file for C++?

### ISSUE THREAD

**Issue by tchen2mmm** [VSoftTechnologies/DUnitX#221]
In the generated DUnitX.TestFramework.hpp file, There are lines:

//-- user supplied -----------------------------------------------------------
#if defined(USEPACKAGES)
# pragma comment(lib, "DUnitXRuntime.bpi")
#else
# pragma comment(lib, "DUnitXRuntime")
#endif

But there seems to be no DUnitXRuntime libraries generated under DUnitX_D10Berlin group project files. Does the "user supplied" comment suggest the user needs to create a library project for the C++ project?

**Comment by vincentparrett** [comment]
I think the CPP stuff was copied in from embarcadero, so for that it might be best to stick with the version they ship (assuming it still works with cbuilder).
