### ISSUE TITLE
Constructor in base fixture class is not called

### ISSUE THREAD

**Issue by michaelstaszewski** [VSoftTechnologies/DUnitX#226]
If you have a base fixture class with a defined constructor and a derived fixture class without a locally defined constructor the base constructor is not called. For example, TBaseTestFixture.Create is not called when TDerivedTestFixture is initialized.

```pascal
TBaseTestFixture = class(TObject)
private
protected
public
  constructor Create; virtual;
  destructor Destroy; override;
end;

[TestFixture]
TDerivedTestFixture = class(TBaseTestFixture)
private
protected
public
  [Test]
  procedure SampleTest;
end;
```

**Comment by michaelstaszewski** [comment]
I have proposed fix I'm about to submit.

**Comment by rpottsoh** [comment]
This can be closed.
