### ISSUE TITLE
I need DUnitX adapter to Allure report subsystem

### ISSUE THREAD

**Issue by cepera-one** [VSoftTechnologies/DUnitX#241]
Allure is great test report tool (http://allure.qatools.ru/). Many xUnit frameworks have adapters to use it transparently while writing tests. It would be nice to have adapter for DUnitX too.

**Comment by vincentparrett** [comment]
This doesn't look like a simple task. Allure looks to be rather invasive, in that whatever test framework you are using, you need to modify your tests, it's not just a case of adding a different output format. I'm happy to take contributions but don't have to time to look at it myself.

**Comment by cepera-one** [comment]
I think it is enough to add new ITestLogger implementation for allure case as a begining. It must write xml of special allure format that you can see here 'https://github.com/allure-framework/allure-demo/tree/master/allure-results'. As you can see here 'https://github.com/allure-framework/allure1/wiki/Creating-Allure-Adapter' it requires just separate xml file for each TestFixture (suite) and has some rules for xml-file names.

**Comment by cepera-one** [comment]
Allure fits into the overall structure of the DUnitX tests. It simply allows you to add additional attributes that are specific to allure, as well as another level of dividing the test into steps.

**Comment by cepera-one** [comment]
I did it. ITestLogger implementation for Allure now available at https://github.com/cepera-one/allure-delphi

**Comment by vincentparrett** [comment]
Nice work. I don't see the need to merge this into DUnitX though - much like allure support for other frameworks where they have separate packages maintained by allure/others rather than the framework authors.
