### ISSUE TITLE
DUnitX fails to install after a build

### ISSUE THREAD

**Issue by anttonis** [VSoftTechnologies/DUnitX#242]
Hi. I am trying to install install DUnitX Wizard. 
In Rio 10.3.2 I load DUnitX_IDE_Expert_D10Rio.dproj, successfully build it, and run Install. 
I get this error:
Cannot load package 'DUnitXIDEExpert260.'  It contains unit 'DUnitX.Expert.ProjectWizardEx', which is also contained in package 'DUnitX_IDE_Expert_D10Rio'.

Can you please advise on how to overcome this

Thank you

**Comment by vincentparrett** [comment]
This sounds like you already have the expert installed when you installed delphi. You would need to remove the embarcadero provided expert before installing from the github source.
