### ISSUE TITLE
Ignore-Attribute for Test-Fixtures

### ISSUE THREAD

**Issue by MalteThomssenORGADATA** [VSoftTechnologies/DUnitX#244]
Hello,

currently the Ignore-Attribute is available for single methods inside a fixture.
It would be great to implement the Ignore-Attribute for a whole fixture e.g.

```
[TestFixture]
[Ignore('Ignore me.')]
TSampleTest = class
  [Test]
  procdure Test_A;
  [Test]
  procdure Test_B;
end;
```

What do you think about this proposal?

**Comment by vincentparrett** [comment]
Agreed.
