### ISSUE TITLE
Registering multiple fixtures with the same name

### ISSUE THREAD

**Issue by MalteThomssenORGADATA** [VSoftTechnologies/DUnitX#245]
Hello,

we've encountered a problem registering multiple fixtures with the same name (class-name).
The RTTI discovery differs from the discovery via the static class `TDUnitX`. The discovery via `TDUnitX `skips one of those tests because `ContainsValue` is used. In my opinion both ways should use the same condition to add a fixture.

static discovery via TDUnitX
```
procedure TDUnitXFixtureProvider.Execute(const context: IFixtureProviderContext);
begin
  // ...

  for pair in TDUnitX.RegisteredFixtures do
  begin
    // checking via value
     if not FFixtureClasses.ContainsValue(pair.Value) then
      FFixtureClasses.AddOrSetValue(pair.Key, pair.Value);
  end;

  // ...
end;
```

RTTI discovery
```
procedure TDUnitXFixtureProvider.RTTIDiscoverFixtureClasses(const context: IFixtureProviderContext);
  // ...
  // checking via key
  if not FFixtureClasses.ContainsKey(TRttiInstanceType(rType).MetaclassType) then
    FFixtureClasses.Add(TRttiInstanceType(rType).MetaclassType,sName);

  // ...
```

What is your opinion on this topic?

**Comment by vincentparrett** [comment]
I will look into this. It's been a while since I looked at this code, need to familiarize myself with it again to understand why this was done.

**Comment by vincentparrett** [comment]
After looking at this, I agree it is incorrect, fix pushed.

**Comment by MalteThomssenORGADATA** [comment]
Thanks
