### ISSUE TITLE
FixInsight findings

### ISSUE THREAD

**Issue by mWaltari** [VSoftTechnologies/DUnitX#249]
[FixInsight Optimization] dunitx.assert.pas(977): O804 Method parameter 'message' is declared but never used
[FixInsight Optimization] dunitx.assert.pas(369): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(378): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(406): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(427): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(434): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(441): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(448): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(471): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(478): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(494): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(503): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(530): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(544): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(567): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(574): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(581): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(588): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(595): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(602): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(614): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(630): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(649): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(663): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(727): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(736): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(759): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(766): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(773): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(780): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(787): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(799): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(811): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(818): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(825): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(832): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(839): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(846): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(858): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(870): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(877): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(884): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(891): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(898): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(905): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(912): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(919): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(926): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(939): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(981): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(1000): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(1026): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(1055): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(1070): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(1099): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(1123): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(1148): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(1166): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(1189): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(1201): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(1211): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Optimization] dunitx.assert.pas(1236): O805 Inline marked routine 'Assert.DoAssert' comes after its call in the same unit
[FixInsight Convention] dunitx.assert.ex.pas(42): C104 Class name 'Assert' should start with 'T'
[FixInsight Warning] dunitx.attributes.pas(409): W525 Missing INHERITED call in constructor
[FixInsight Warning] dunitx.attributes.pas(416): W525 Missing INHERITED call in constructor
[FixInsight Warning] dunitx.attributes.pas(424): W525 Missing INHERITED call in constructor
[FixInsight Warning] dunitx.attributes.pas(431): W525 Missing INHERITED call in constructor
[FixInsight Warning] dunitx.filters.pas(262): W525 Missing INHERITED call in constructor
[FixInsight Warning] dunitx.filters.pas(268): W525 Missing INHERITED call in constructor
[FixInsight Warning] dunitx.filters.pas(274): W525 Missing INHERITED call in constructor
[FixInsight Convention] dunitx.consolewriter.base.pas(88): C110 Getter or setter name is different from property declaration
[FixInsight Convention] dunitx.consolewriter.base.pas(88): C110 Getter or setter name is different from property declaration
[FixInsight Warning] dunitx.testrunner.pas(251): W519 Method 'TDUnitXTestRunner.AddStatus' is empty
[FixInsight Warning] dunitx.testrunner.pas(347): W525 Missing INHERITED call in constructor
[FixInsight Warning] dunitx.testrunner.pas(355): W525 Missing INHERITED call in constructor
[FixInsight Warning] dunitx.testrunner.pas(341): W534 Class instance 'Self' passed to 'Create' but interface expected
[FixInsight Optimization] dunitx.testrunner.pas(593): O804 Method parameter 'context' is declared but never used
[FixInsight Optimization] dunitx.testrunner.pas(593): O804 Method parameter 'threadId' is declared but never used
[FixInsight Optimization] dunitx.testrunner.pas(615): O804 Method parameter 'context' is declared but never used
[FixInsight Optimization] dunitx.testrunner.pas(615): O804 Method parameter 'threadId' is declared but never used
[FixInsight Optimization] dunitx.testrunner.pas(665): O804 Method parameter 'context' is declared but never used
[FixInsight Optimization] dunitx.testrunner.pas(665): O804 Method parameter 'threadId' is declared but never used
[FixInsight Optimization] dunitx.testrunner.pas(701): O804 Method parameter 'context' is declared but never used
[FixInsight Optimization] dunitx.testrunner.pas(701): O804 Method parameter 'threadId' is declared but never used
[FixInsight Optimization] dunitx.testrunner.pas(709): O804 Method parameter 'context' is declared but never used
[FixInsight Optimization] dunitx.testrunner.pas(887): O804 Method parameter 'context' is declared but never used
[FixInsight Optimization] dunitx.testrunner.pas(887): O804 Method parameter 'threadId' is declared but never used
[FixInsight Convention] dunitx.utils.pas(381): C110 Getter or setter name is different from property declaration
[FixInsight Convention] dunitx.utils.pas(382): C110 Getter or setter name is different from property declaration
[FixInsight Convention] dunitx.utils.pas(383): C110 Getter or setter name is different from property declaration
[FixInsight Optimization] dunitx.utils.pas(898): O804 Method parameter 'ASource' is declared but never used
[FixInsight Optimization] dunitx.utils.pas(898): O804 Method parameter 'ATarget' is declared but never used
[FixInsight Optimization] dunitx.utils.pas(898): O804 Method parameter 'AResult' is declared but never used
[FixInsight Warning] dunitx.memoryleakmonitor.default.pas(75): W519 Method 'TDUnitXDefaultMemoryLeakMonitor.PostSetUp' is empty
[FixInsight Warning] dunitx.memoryleakmonitor.default.pas(80): W519 Method 'TDUnitXDefaultMemoryLeakMonitor.PostTearDown' is empty
[FixInsight Warning] dunitx.memoryleakmonitor.default.pas(85): W519 Method 'TDUnitXDefaultMemoryLeakMonitor.PostTest' is empty
[FixInsight Warning] dunitx.memoryleakmonitor.default.pas(90): W519 Method 'TDUnitXDefaultMemoryLeakMonitor.PreSetup' is empty
[FixInsight Warning] dunitx.memoryleakmonitor.default.pas(95): W519 Method 'TDUnitXDefaultMemoryLeakMonitor.PreTearDown' is empty
[FixInsight Warning] dunitx.memoryleakmonitor.default.pas(100): W519 Method 'TDUnitXDefaultMemoryLeakMonitor.PreTest' is empty
[FixInsight Optimization] dunitx.fixtureproviderplugin.pas(544): O804 Method parameter 'context' is declared but never used

**Comment by vincentparrett** [comment]
FixInsight results very much depend on the settings you have for it. I did just fix some but most are due to the use of interfaces or there are unused constants that are there because we might want to use them later.

**Comment by mWaltari** [comment]
Yes. I just put them all out there, so you can make decision what you think are worth reacting to.
