### ISSUE TITLE
Incorrect XML report generated when registering more than one fixture declared in a non-namespaced unit (fix included in the issue)

### ISSUE THREAD

**Issue by ghost** [VSoftTechnologies/DUnitX#253]
https://github.com/VSoftTechnologies/DUnitX/blob/12c4c6f0305b2a5065438a5ccb0d9c8f79c3fb39/Source/DUnitX.FixtureProviderPlugin.pas#L177

This
```pascal
if not tmpFixtures.TryGetValue(fixtureNamespace,parentFixture) then
```
should fix it (the `parentFixture` will be filled with an existing fixture after the first iteration for a fixture declared in a non-namespaced unit).

**Comment by dsogari** [comment]
Possibly also replace the following check: https://github.com/VSoftTechnologies/DUnitX/blob/12c4c6f0305b2a5065438a5ccb0d9c8f79c3fb39/Source/DUnitX.FixtureProviderPlugin.pas#L207

By an assertion like
```pascal
System.Assert(Assigned(parentFixture));
```
since I believe it would always be assigned.

**Comment by vincentparrett** [comment]
Thanks, fixed.
