### ISSUE TITLE
Remove XPMan from DUnitX.Loggers.GUI.VCL.pas

### ISSUE THREAD

**Issue by zedalaye** [VSoftTechnologies/DUnitX#255]
Because it creates a resource duplicate with Delphi auto-generated manifests.

Builind a project that contains this unit leads to this warning :

`[dcc32 Conseil] H2161 Warning: Duplicate resource:  Type 24 (user-defined), ID 1; File D:\Code\delphi\projets\nextis\ui\Neptis.res resource kept; file c:\program files (x86)\embarcadero\studio\20.0\lib\Win32\release\WindowsXP.res resource discarded.`

Removing XPMan solve the problem.

**Comment by vincentparrett** [comment]
Fixed.
