### ISSUE TITLE
Quote logs expected and actual values

### ISSUE THREAD

**Issue by mWaltari** [VSoftTechnologies/DUnitX#257]
In case of strings anyways
Expected YYYY is not equal to actual Parameter XXX seems to be off

And if you add some custom message but not values yourself, you don’t see the empty value right of the bat.

Expected “YYYY” is not equal to actual ““ Parameter XXX seems to be off Would be visually much faster to parse

**Comment by vincentparrett** [comment]
I would prefer brackets on this
Expected [YYYY] is not equal to actual []

**Comment by luebbe** [comment]
I'd like to have a go at this.
Is it ok if
* I wrap the expected vs actual for all data types, not just strings, in brackets?
* I make some of the phrases consistent?
  We have:
    * "expected .. is not equal to actual .."
    * "expected .. but got .."
I'd like to keep only the second one, because it is shorter
* Fix some inconsistent capitalization

**Comment by vincentparrett** [comment]
Yep, go for it.
