### ISSUE TITLE
Make XML output compatible with Gitlab CI

### ISSUE THREAD

**Issue by SlMaker** [VSoftTechnologies/DUnitX#258]
Unfortunately Gitlab cannot read/understand the generated XML output from DUnitX.
**More infos**: https://docs.gitlab.com/ee/ci/junit_test_reports.html

**Limitations**
Currently, the following tools might not work because their XML formats are unsupported in GitLab.
- <testcase> does not have classname attribute (https://gitlab.com/gitlab-org/gitlab-foss/-/issues/50964)  

-> This resulted in adding classname to eslint (https://github.com/eslint/eslint/pull/11683).

Maybe something similar could allow using DUnitX with Gitlab CI? Or does it need more changes?

**Comment by vincentparrett** [comment]
DUnitX generates NUnit format xml. This is done by a logger class, it should be simple to create a logger to produce JUnit xml. Happy to accept a PR for this if someone want's to have a go, I don't currently have the time to work on it (and all the tools I use work with nunit style xml).
