### ISSUE TITLE
Depencendy issue in Expert

### ISSUE THREAD

**Issue by mWaltari** [VSoftTechnologies/DUnitX#266]
Cannot load package 'DUnitX_IDE_Expert_D10Tokyo.' It contains unit 'DUnitX.Expert.ProjectWizardEx', which is also contained in package 'DUnitXIDEExpert260'.

Is this caused by DUnitX that came with Delphi or some other issue, don't have clue. 

with Latest versio from GitHUB.

**Comment by vincentparrett** [comment]
If you are installing from the version on github you must first remove the version that shipped with delphi. Embarcadero rename the packages to suite their naming convention.

**Comment by mWaltari** [comment]
Do you have any idea which files and from where I need to remove, any how to tutorial in Wiki etc?

**Comment by vincentparrett** [comment]
In the IDE, on the Component menu, Install Packages, remove the DUnitX Expert package.

**Comment by mWaltari** [comment]
I believe I did, have to recheck.

**Comment by mWaltari** [comment]
Found if, it was named something like "Embarcadero Unit testing IDE expert" etc... Did not write it down. Sorry.
