### ISSUE TITLE
Allow splitting tests in to child processes

### ISSUE THREAD

**Issue by Torbins** [VSoftTechnologies/DUnitX#268]
One of our tests is causing memory corruption. Tests, running after it, randomly fail. I do not know exactly which test is causing problems, and want to isolate a few suspicious ones in to a separate process. The problem is, that child process will have to transfer execution results back to the parent, so that parent will be able to create final XML. I have quickly looked at DUnitX code, and it looks like this scenario is not supported. Probably, I will have to write some custom code. Where should I start, which classes are best suited for my needs?

**Comment by vincentparrett** [comment]
Making tests run in a separate process would be a massive task. 

A simpler option would be to make use of the [filtering options](https://www.finalbuilder.com/resources/blogs/dunitx-updated-filtering-tests) to limit which tests run and try to narrow it down that way. 

You could also use FastMM4's debugging options to see if that helps.

**Comment by Torbins** [comment]
Thanks, that will help. I want to make this process automatic. Is there some existing code that parses XML or console output? It's, probably, not hard, but if there are some caveats, I would like to have a ready-made solution.

**Comment by vincentparrett** [comment]
If you think it's simple go for it.. as for a ready made solution, none exists - I certainly do not have the time to work on this. If your tests are causing memory corruption the only options is to just run a few at a time and use the memory manager or other tools (like madExcept) to help pinpoint when/where that is happening.

**Comment by Torbins** [comment]
No, I am going to use filtering options and disable tests by a few at a time, then run tests, analyse errors, and decide what to do next. It would be nice to have a program, that does this automatically, because I have a few thousand tests, and such situations can happen in future. So I will need to parse test results.
