### ISSUE TITLE
Compile error on Delphi 10.3

### ISSUE THREAD

**Issue by ahmadrasyidsalim** [VSoftTechnologies/DUnitX#275]
I got an error when I trying to install DUnitX following the step from the wiki, exactly on this link: https://github.com/VSoftTechnologies/DUnitX/wiki/Wizard-Installation:

I'm using:
```
Embarcadero® Delphi 10.3 Version 26.0.36039.7899 
Copyright © 2019 Embarcadero Technologies, Inc. All Rights Reserved.
```

Here's the log:
```
[dcc32 Fatal Error] DUnitX.Expert.CodeGen.SourceFile.pas(31): F1026 File not found: 'DUnitX.inc'
```

**Comment by vincentparrett** [comment]
Please pull again, I have updates the search paths in the dproj file to fix this.

**Comment by ahmadrasyidsalim** [comment]
It works, thanks to you, I got no error _on compile_. on _install_ I got a new one @vincentparrett 

```
Cannot load package 'DUnitXIDEExper260.' It contains unit 'DUnitX.Expert.ProjectWizardEx', which also contained in package 'DUnitX_IDE_Expert_D10Rio'
```

**Comment by vincentparrett** [comment]
Looks like you still have the version shipped with rad studio, uninstall that one first.

**Comment by ahmadrasyidsalim** [comment]
Now everything is working like a charms 💥
