### ISSUE TITLE
Request for OnlyTest attribute

### ISSUE THREAD

**Issue by raelb** [VSoftTechnologies/DUnitX#279]
Hi,
It would be very useful if there was an `OnlyTest` (or something similar) attribute, that I could use to temporarily ignore all tests except those marked with `OnlyTest`. When I am creating a new test it is more efficient to only run that test and no others.

**Comment by luebbe** [comment]
I'd recommend you to install TestInsight and use its GUI to select the tests that you want to run.

**Comment by vincentparrett** [comment]
What luebbe said, TestInsight can be found here - https://bitbucket.org/sglienke/testinsight/wiki/Home
