### ISSUE TITLE
Wrong values for Duration and FinishTime in TDUnitXFixtureResult

### ISSUE THREAD

**Issue by ChristianHeitzer** [VSoftTechnologies/DUnitX#286]
The values for the properties Duration and FinishTime in TDUnitXFixtureResult are set to wrong values. You can see this for example in the output result of the TDUnitXXMLJUnitLogger. The first testsuite node has the same time attribute value as the upper most overall testsuite node. Then from top to bottom of the file the time attribute value gets lower for every listed testsuite node.

We use the junit file for visualizing the test results on our jenkins server. The according jenkins plugin does not use the time attribute value of the upper most testsuite node but summarizes the individual time attribute values. This results in strange overall execution times of several hours, while in real the execution of the tests just took a few minutes.

I investigated the code and found this as reason:

- In TDUnitXTestRunner.ExecuteFixtures for every processed fixture a TDUnitXFixtureResult instance gets created.
- TDUnitXFixtureResult.Create initiates a TStopWatch.CreateNew.
- After all fixtures have been processed a RollUpResults gets called in TDUnitXTestRunner.Execute for every formerly processed fixture.
- In TDUnitXFixtureResult.RollUpResults TStopWatch.Stop gets called at that moment and StopWatch.Elapsed gets set as Duration for the fixture. Also FinishTime gets set at this moment to the current time stamp.
- Since all fixtures got started at different times, but stopped ("rolled up") all nearly at the same end time, you get wrong calculated values in consequence.

A solution as far as i can tell could be:

In TDUnitXTestRunner.ExecuteFixtures there should be a call to RollUpResults for every test fixture right after it's execution.

```
procedure TDUnitXTestRunner.ExecuteFixtures(const parentFixtureResult : IFixtureResult; const context: ITestExecuteContext; const threadId: TThreadID; const fixtures: ITestFixtureList);
var
  fixture: ITestFixture;
  fixtureResult : IFixtureResult;
begin
  for fixture in fixtures do
  begin
    ...
    Self.Loggers_StartTestFixture(threadId, fixture as ITestFixtureInfo);
    try
      ...
      // RollUpResults for fixture. Otherwise this just gets done in TDUnitXTestRunner.Execute right after ExecuteFixtures.
      (fixtureResult as IFixtureResultBuilder).RollUpResults;
    finally
      Self.Loggers_EndTestFixture(threadId, fixtureResult);
    end;
  end;
end;
```

**Comment by vincentparrett** [comment]
Thanks, I just pushed a fix for this - not sure how I never noticed this before. The timings make a lot more sense now!
