### ISSUE TITLE
Question about JUnit output

### ISSUE THREAD

**Issue by luebbe** [VSoftTechnologies/DUnitX#287]
Hi Folks,

The JUnit output always contains a non-existent "summary" testsuite in the first row

```
<testsuites>
  <testsuite name="Path\to\Tests.exe" tests="377" skipped="0" errors="0" failures="1" time="0.108" timestamp="2021-07-21T15:53:35" />
  ...
  <testsuite  name="...">
  </testsuite>
```

doesn't this summary information belong into the `<testsuites>` node?
```
<testsuites name="Path\to\Tests.exe" tests="377" skipped="0" errors="0" failures="1" time="0.108">
  <testsuite  name="...">
  </testsuite>
  ...
  <testsuite  name="...">
  </testsuite>
```

Reference: [JUnit 5 xsd](https://github.com/junit-team/junit5/blob/main/platform-tests/src/test/resources/jenkins-junit.xsd)

**Comment by vincentparrett** [comment]
This looks like a bug to me, the junit logger was an [external contribution](https://github.com/VSoftTechnologies/DUnitX/pull/273)  - based on [this article](https://help.catchsoftware.com/display/ET/JUnit+Format) - the xsdl there doesn't show the aggregation on the testsuites. 

I couldn't find an xsd for earlier versions of junit so not sure if this is a change from earlier versions or not -  but it seems wrong to me - happy to take a PR to fix this (very time poor at the moment).

**Comment by luebbe** [comment]
I found xsd files for JUnit 3,4,5 (didn't search for older ones) and they all have this section:

``` 
    <xs:element name="testsuites">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="testsuite" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="optional"/>
            <xs:attribute name="time" type="xs:string" use="optional"/>
            <xs:attribute name="tests" type="xs:string" use="optional"/>
            <xs:attribute name="failures" type="xs:string" use="optional"/>
            <xs:attribute name="disabled" type="xs:string" use="optional"/>
            <xs:attribute name="errors" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>
```
so probably the xsd on which the article was based, wasn't correct. I'll send a PR.
