### ISSUE TITLE
--exclude and Categories don't seem to work

### ISSUE THREAD

**Issue by Nic-Alexander** [VSoftTechnologies/DUnitX#288]
I have added the exclude parameter --exclude:SlowTests and added the attribute [Category('SlowTests')] to a test, but it still gets run.   Am I missing something?

**Comment by vincentparrett** [comment]
I just tried this and it works fine. One thing to check is that you have this

````delphi
    //Check command line options, will exit if invalid
    TDUnitX.CheckCommandLine;
````
at the start of your test project - if not you probably created it using an older version of DUnitX  - create a new DUnitX project using the project wizard and then compare it's dpr to yours.

**Comment by Nic-Alexander** [comment]
Yes, that was the solution; thanks very much!
