### ISSUE TITLE
TestInsight and file name clashes

### ISSUE THREAD

**Issue by luebbe** [VSoftTechnologies/DUnitX#291]
Two things I noticed while working on the two fixes:
1. The test program doesn't compile when testinsight is defined. Some defines have to be juggled around to fix this
2. both NUnit and JUnit XML loggers have the same default file name `dunit-results.xml` which results in a file access error when you add both loggers to the project without overriding the file name.

I think:
1. should be fixed and
2. could be fixed, by changing `dunit-results.xml` to e.g. `dunit-results.junit.xml` and `dunit-results.nunit.xml`, but this will probably break existing CI configurations.

**Comment by vincentparrett** [comment]
1) This is fixed now
2) This will break existing setups. Also it would be unusual to have both an NUnit logger and a JUnit Logger in the same app. You can supply an output filename to the logger constructor if you need to change it.

**Comment by luebbe** [comment]
1. Thanks, saw it
2. Not a real problem as you say, becaue normally only one of the two loggers would be used, I just stumbled across it, because I added a JUnit logger without removing the NUnit logger when I worked on the JUnit output :)
