### ISSUE TITLE
FTestName (not) in DUnitCompatibility.TTestCase 

### ISSUE THREAD

**Issue by goulu** [VSoftTechnologies/DUnitX#299]
shouldn't we add  FTestName to DUnitCompatibility.TTestCase as DUnit has one ?

if nobody's already on this, I'll implement it according to https://stackoverflow.com/questions/64822239/delphi-dunitx-how-do-i-get-the-name-of-the-test-currently-running (or can you think of a simpler way ?)

**Comment by vincentparrett** [comment]
I just pushed a change which resolves this.
