### ISSUE TITLE
Any way to set UseRTTI to true when using a visual runner/logger?

### ISSUE THREAD

**Issue by nandod** [VSoftTechnologies/DUnitX#307]
When using f. ex. TGUIVCLTestRunner there's no way to set the runner's UseRTTI property to True; it could be added as a property to the form, or added as an option, or even surfaced in the gui and persisted. Or it could even be set to True by default.
What's the preferred approach?

**Comment by vincentparrett** [comment]
The UseRTTI option is intended to be set at startup, changing it after the application has started will have no effect.  Set it to true in your dpr and forget it. It has limited utility anyway, due to the linker removing unreferenced classes - better to register test fixture classes manually.

**Comment by nandod** [comment]
At startup is fine, and ahat's what I did but I had to expose it in TGUIVCLTestRunner because otherwise there's no way to set it in the runner that is created internally.
Would you accept a pull request for that? It's really 3 lines of code.
About registering, to each his own I guess. In my case the linker is taken care of by {$STRONGLINKTYPES ON} (which in my app is required anyway for loose coupling) and I find the RTTI way more convenient and less error-prone.
