### ISSUE TITLE
SetUp/TearDown exactly once for all test methods in a TestCase ?

### ISSUE THREAD

**Issue by alan008** [VSoftTechnologies/DUnitX#311]
I'm migrating from DUnit to DUnitX. Everything seems fine, but I'm lacking one piece of functionality.
In DUnit there was a way to execute SetUp/TearDown not for every Test method in TestCase, but once for the whole TestCase (once for all methods inside TestCase).
This was made but TTestSetup class, in which SetUp and TearDown were overriden, and registration of the test case was special:
not just 
RegisterTest(TSomeTestCase.Suite)
but
RegisterTest(TSomeTestSetup.Create(TSomeTestCase.Suite))
SetUp and TearDown were in TSomeTestSetup class and they were called one time for all Test methods inside TSomeTestCase.

Is there something similar in DUnitX? My SetUp method is slow (it connects to some server), so its not convinient to reconnect for every test method execute. I want to connect once and then execute all test methods (100+ of them) and then disconnect.

**Comment by vincentparrett** [comment]
SetupFixture and TeardownFixture attributes are what you are looking for,

**Comment by alan008** [comment]
Not sure, what am I doing wrong. I've created empty example in Delphi 11 Alexandria (with built-in version of DUnitX) , wrote [Setup], [TearDown], [SetupFixture], [TeardownFixture] attributes, but these methods are not called

[DUnit_Test.zip](https://github.com/VSoftTechnologies/DUnitX/files/7949962/DUnit_Test.zip)
![2022-01-27_14-14-45](https://user-images.githubusercontent.com/2262134/151349187-13c500ce-a05d-4ec2-b643-db568122b38f.png)

**Comment by alan008** [comment]
Ahh, must be PUBLIC methods. The more you live the more you know...
