### ISSUE TITLE
Small but annoying typo

### ISSUE THREAD

**Issue by sonjli** [VSoftTechnologies/DUnitX#316]
In this line there is a #0 and not a #10 that cut the project in a new wizard:

https://github.com/VSoftTechnologies/DUnitX/blob/402bfc20da7e1ddb3b94086cb13aaff65ff92764/Expert/DUnitX.Expert.CodeGen.Templates.pas#L58

**Comment by vincentparrett** [comment]
Thanks, just pushed a fix.
