### ISSUE TITLE
fix commandline help documentation for exitbehavior

### ISSUE THREAD

**Issue by edgimar** [VSoftTechnologies/DUnitX#318]
The documentation on [this](https://github.com/VSoftTechnologies/DUnitX/blob/8bb223c55b66bc159b5c8497537d80c3bd81f3f4/Source/DUnitX.OptionsDefinition.pas#L105) line is wrong -- the current default is to continue, not pause.

**Comment by vincentparrett** [comment]
Fixed thanks.
