### ISSUE TITLE
DUnitX xml does not set the namespace in the output properly

### ISSUE THREAD

**Issue by markhumphreysjhc** [VSoftTechnologies/DUnitX#322]
After tests have been run, the resulting `dunitx-results.xml` file only has the name of the tests, and not the full namespace.

'Proper' NUnit output looks like this ...

`<test-case name="NUnit.Tests.Assemblies.MockTestFixture.InconclusiveTest" executed="True" result="Inconclusive" success="False" time="0.001" asserts="0">`

whereas DUnitX looks like this ...

`<test-case name="TestExecute" executed="True" result="Success" success="True" time="0.000" asserts="0" />`

This means that when this file is interpreted by Jenkins, all the unimaginatively name tests end up grouped together.

It looks like a one line change to `DUnitX.Loggers.XML.NUnit.pas`, on line 336, using the `FullName` property correctly outputs the full namespace.

`sName := EscapeForXML(testResult.Test.FullName);`

**Comment by vincentparrett** [comment]
> 'Proper' NUnit output looks like this ...

That's not quite correct. The name attribute is just the test name - what is missing is the fullname attribute (not sure why we never added it before). I will push a fix for this shortly.

**Comment by vincentparrett** [comment]
FYI, the Jenkins NUnit plugin just converts the xml to JUnit format - so perhaps switching to the DUnitX JUnit logger might yield better results.
