### ISSUE TITLE
Proper support for TAlphaColor and TColor param

### ISSUE THREAD

**Issue by viniciusfbb** [VSoftTechnologies/DUnitX#323]
Test case of TAlphaColor or TColor parameters work but not optimally. TAlphaColor and TColor types of Cardinal/Integer respectively and this is how it is handled in a string conversion of TestCase parameters.

However, the ideal would be a specific treatment for these parameters, as it is much more readable for me to write "Red" than the integer that represents red.

Based on that, I propose that the ideal would be to try to convert TAlphaColor parameters, from string to Cardinal (TryStrToUInt), and if it fails, use System.UIConsts.StringToAlphaColor(). Follow the same logic for TColor.

**Comment by vincentparrett** [comment]
I had a quick look System.UIConsts and see it doesn't reference any vcl stuff.. so happy to take a PR for this.
