### ISSUE TITLE
Change in FExitBehavior

### ISSUE THREAD

**Issue by fabiohmribeiro** [VSoftTechnologies/DUnitX#339]
Good morning! I would like to understand the reason for the change below:

Before Delphi 12:
FExitBehavior := TDUnitXExitBehavior.Pause;

In Delphi 12:
FExitBehavior := TDUnitXExitBehavior.Continue;

With this change, the test on Windows no longer keeps the console paused, requiring intervention in the DPR code.

**Comment by vincentparrett** [comment]
This change was actually made 4 years ago

https://github.com/VSoftTechnologies/DUnitX/commit/d27b99b07f7e7f5e07f1da202f61b3553846dfb2

If you are using the version shipped with delphi then it's probably just they they only recently pulled in that change. 

You can of course change the property in your project 

````delphi
TDUnitX.Options.ExitBehavior := TDUnitXExitBehavior.Pause;
````
