### ISSUE TITLE
StrToUInt64Def is not available in XE5

### ISSUE THREAD

**Issue by lbcsy** [VSoftTechnologies/DUnitX#345]
There is a compile error in Delphi XE5:

[dcc32 Error] DUnitX.Utils.pas(1218): E2003 Undeclared identifier: 'StrToUInt64Def'

StrToUInt64Def seems defined in later version of Delphi but not in XE5.

**Comment by vincentparrett** [comment]
Thanks for the report, just pushed a fix - untested, not sure how else to address this. It should at least compile.
