### ISSUE TITLE
Passing tab character within string of a parameter in test case?

### ISSUE THREAD

**Issue by DaveMartel** [VSoftTechnologies/DUnitX#351]
I have not found any way to pass characters like #9, #13, #10 as part of a string in the parameters for test cases. This is needed when I am testing a routine to remove these and want to use parameterized tests. I can write individual tests without parameters and code it as part of the text, but it would be good to do something like 

```
    [Test]
    [TestCase('RemoveTAB', 'A#9B', AB')]
    procedure TestRemoveControlChar(const InputString: string; const ExpectedResult: string);

```
In the routine to test handles a number of valid control characters, and it would be nice to have a test for each do with parameters. Just can't work out how to do it.

I have tried adding " around the string, but the " characters become party of the parameters.

**Comment by vincentparrett** [comment]
Delphi does not support escaping characters like that, and the values part is a single string field.

this should work
````delphi
    [TestCase('RemoveTAB', 'A' + #9 + 'B,AB')]
    procedure TestRemoveControlChar(const InputString: string; const ExpectedResult: string);
````
Note the comma to separate the values. See - DUnitX.Attributes TestCaseAttbute class.

**Comment by DaveMartel** [comment]
**Thank you @vincentparrett**. I had tried various combinations, but that one I had missed. The only one I am now having issues with is #0, which obviously is quite a special character. It is just the code I am porting (and testing) is from c++. Not sure if I will ever see #0 in this project, but I would ideally like to have it working. The set of characters I am removing are #0#9#10#11#12#13#32. The actual code is in fact working, which is the goal  (so the tests are not needed for now, but we should always have our tests ready for code changes... :-). 

I just can't test #0 now...

Happy Christmas.
