### ISSUE TITLE
Does the DUnitXFiremonkeyGUI_XE5 project work yet?

### ISSUE THREAD

**Issue by embradded** [VSoftTechnologies/DUnitX#39]
I'm having trouble getting this to build.  It appears the project file is missing several dependencies (DUnitX.Extensibility.pas, DUnitX.Extensibility.PluginManager.pas, and DUnitX.FixtureProviderPlugin.pas).

After adding these dependencies to the project, I get the following build errors:
[dcc32 Error] DUNitX.Loggers.GUIX.pas(80): E2003 Undeclared identifier: 'ITestFixtureList'
[dcc32 Error] DUNitX.Loggers.GUIX.pas(85): E2005 'ITestFixtureList' is not a type identifier
[dcc32 Error] DUNitX.Loggers.GUIX.pas(141): E2005 'ITestFixtureList' is not a type identifier
[dcc32 Error] DUNitX.Loggers.GUIX.pas(143): E2003 Undeclared identifier: 'ITestFixture'
[dcc32 Error] DUNitX.Loggers.GUIX.pas(144): E2003 Undeclared identifier: 'ITest'

I'd really like to have a look at the GUI.  If this is something that is not quite ready for prime time, is it something that is still on the DUnitX roadmap?

**Comment by Nashev** [comment]
On the page https://github.com/VSoftTechnologies/DUnitX in Readme it's feel like any own GUI is deprecated here, in favor of using TestInsight (https://bitbucket.org/sglienke/testinsight/wiki/Home)
