### ISSUE TITLE
Implement MaxTime Attribute

### ISSUE THREAD

**Issue by vincentparrett** [VSoftTechnologies/DUnitX#66]
MaxTime attribute would allow failing a test if it takes longer than the specified time. Useful for detecting major perfomance changes when running tests, ie if you know a test usually takes less than say 2 seconds, then add
`[MaxTime(2000)]`
If it takes longer than 2 seconds then the test will be marked as a failure.

**Comment by MartinSedgewick** [comment]
What about using https://code.google.com/p/delphitimeouts/ as a way to do this?

I would be happy to try implmenting this feature if this way of causing a timeout is ok.

**Comment by vincentparrett** [comment]
Yes, this looks like it might work, but I don't like taking dependencies on other projects so would need to re-implement the idea (there's not much too it anyway).

**Comment by MartinSedgewick** [comment]
OK, I will give it a go and see what I come up with. Might be in a few days...

**Comment by MartinSedgewick** [comment]
Please review the pull request for the initial implementation.

I have gotten it working through adding a optional parameter to TDUnitXTest.AddTest and I have created 3 unit tests to show it works.

I have not looked at AddTestCase yet and not sure what the difference is as yet.

Please let me know any further changes to be made.

**Comment by vincentparrett** [comment]
Looks like you reverted your changes for this pull request? Can you pick them out of the old commit and add them to a new pull request? I'd really like to see this feature added.

**Comment by vincentparrett** [comment]
Ping Martin.. what happened to this feature?

**Comment by MartinSedgewick** [comment]
Sorry Vincent, I got sidetracked earlier this year with work and home life.
I just never got around to finishing this off.

I will try and sort this out soon.

Hope you are doing well

**Comment by staticcat** [comment]
Original attempt at pr #98

**Comment by staticcat** [comment]
Should be implement by pr #121 now. If someone could review to make sure I have implemented this in a satisfactory manor that would be great. 

Thanks goes to @MartinSedgewick for the initial implementation that I cheery picked from.

**Comment by staticcat** [comment]
With the pr merged this issue is completed. Thanks for all those that helped out :+1:
