### ISSUE TITLE
GUI Runner - VCL

### ISSUE THREAD

**Issue by vincentparrett** [VSoftTechnologies/DUnitX#69]
DUnitX lacks a GUI runner like DUnit's. I plan on working on this next (VCL Only).

**Comment by sglienke** [comment]
Can be closed, right?

**Comment by jkaster** [comment]
I certainly think TestInsight fits the bill :)

**Comment by vincentparrett** [comment]
Yes, closing. I was actually working on the same sort of thing as test insight but stephan beat me to it, I use testinsight all the time now, certainly fits the bill.

**Comment by fabriciocolombo** [comment]
Really cool.

I think it's good add a link to the project (I had to go to google).
[TestInsight - unit testing like a pro](http://delphisorcery.blogspot.com.br/2015/02/testinsight-unit-testing-like-pro.html)

**Comment by Nashev** [comment]
Better add a comment with link to https://bitbucket.org/sglienke/testinsight/wiki/Home into the wizard generated projects...
