### ISSUE TITLE
Test failure if no assertions were made

### ISSUE THREAD

**Issue by jensweigele** [VSoftTechnologies/DUnitX#77]
It would be nice that test-methods fail if they don't do an assertion-call (maybe changeable with an attribute).

**Comment by vincentparrett** [comment]
This is now implmented, see FailsOnNoAsserts on the TestRunner. I used your idea, but made it work by using the current thread id as the key for storing the assert counts. We don't have multithreaded tests yet, so at this stage I can only say that it works great for single threaded tests ;)
