### ISSUE TITLE
Test with RepeatTest attribute does not call Setup or Teardown

### ISSUE THREAD

**Issue by MartinSedgewick** [VSoftTechnologies/DUnitX#96]
When a test has RepeatTest attribute, the Setup and Teardown methods are not called.

From what I can tell, when a repeated test is created, a childfixture is added to the current fixture. This child fixture is never assigned the Setup or Teardown methods from the current fixture. I believe if this is added, it will solve the problem.

If this is accepted, then I also think a test (or 2) should be added to the TTestRepeatAttribute in DUnitX.Tests.TestFixture.

**Comment by vincentparrett** [comment]
Yep, looks like a bug, will look into it.

**Comment by vincentparrett** [comment]
Fixed.
