### ISSUE TITLE
Unit tests fail to compile

### ISSUE THREAD

**Issue by sglienke** [VSoftTechnologies/DUnitX#97]
The XE7 project contains madExcept units in the dpr (probably added by the madExcept IDE plugin by the last commiter)

Some tests contain references to Delphi.Mocks (is it intended that the project is not self contained?)
Also afaik Delphi Mocks does not work on XE.

On XE tests fail to compile with an AV even before reaching the part where Delphi Mocks is used.
As there was no test project for XE, I used the XE2 one

**Comment by vincentparrett** [comment]
I think that was my fault, I have removed the references from the dpr. Yes the tests have a dependency on Delphi-Mocks, but the framework does not. The tests will not compile on XE.
